steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/charged-garden-229009/my-image', '.']
  timeout: 50s
  env:
  - 'TEST_ENV=test-env-value'
  - 'PROJECT_ID=$PROJECT_ID'
images: ['gcr.io/charged-garden-229009/my-image']

